# Generated by Django 5.1 on 2024-08-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0002_envoyer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envoyer',
            name='password',
            field=models.CharField(max_length=60),
        ),
    ]
