# Generated by Django 5.1 on 2024-08-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0003_alter_envoyer_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='recevoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creer', models.CharField(max_length=50)),
            ],
        ),
    ]
