# Generated by Django 5.1 on 2024-08-28 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0005_delete_recevoir'),
    ]

    operations = [
        migrations.DeleteModel(
            name='envoyer',
        ),
    ]
