# Generated by Django 5.1 on 2024-08-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appli', '0006_delete_envoyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='envoyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
    ]
